# Generated by Django 4.2.2 on 2023-07-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
