# Generated by Django 4.2.2 on 2023-07-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_home_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
